pipline을 main에서 사용할 수 있도록 변경
slink-to-unlock/rpi-snailshell pull request #10
Opened 2024-02-24 09:00 UTC by zzangsu

2024-02-24 09:02 UTC, ahnsukwoo approved these changes

2024-02-24 09:04 UTC, ProtossDragoon requested changes

2024-02-24 09:04 UTC, ProtossDragoon commented on snailshell/pipeline.py
> +        cap = cv2.VideoCapture(0)
이거 얼굴 보이는거야? 신기하네

2024-02-24 09:04 UTC, ProtossDragoon commented on snailshell/pipeline.py
> +    print(frame_width)
어떤 것을 출력하는지 태그도 있으면 좋을것같아

2024-02-24 09:04 UTC, ProtossDragoon commented on snailshell/pipeline.py
> +        cap = cv2.VideoCapture(0)
@dhynxdhyn 다현누나가 만들었었던 라즈베리파이카메라 로드 소스코드랑 합칠 수 있으려나?

2024-02-24 09:05 UTC, ProtossDragoon commented on snailshell/pipeline.py
> +        cap = cv2.VideoCapture(0)
이걸 라즈베리 파이 카메라 연결로만 변경해서 작동 테스트하면 됨

2024-03-02 07:06 UTC, ProtossDragoon approved these changes

2024-03-02 07:07 UTC, merged