model_class 생성, 수정사항 반영
slink-to-unlock/rpi-snailshell pull request #12
Opened 2024-03-02 08:56 UTC by ahnsukwoo

2024-03-02 09:00 UTC, ProtossDragoon commented on snailshell/model_loader.py
> +        model.classifier[1] = torch.nn.Linear(in_features, 2)
@zzangsu 쌔삥

2024-03-02 09:01 UTC, zzangsu commented on snailshell/model_loader.py
> +        model.classifier[1] = torch.nn.Linear(in_features, 2)
linear가 새거에요

2024-03-02 17:16 UTC, ProtossDragoon requested changes
굳굳! 고생했다 처음보다 훨씬 나아졌어
수정사항 확인 부탁~

2024-03-02 17:16 UTC, ProtossDragoon commented on snailshell/model_loader.py
> +print(do_inferance(img_array, model, model_name))
여기 테스트하는부분 제거가 안된것같다이

2024-03-02 17:16 UTC, ProtossDragoon commented on snailshell/pipeline.py
> +    weight_path = "examples/microsoft_resnet-50_240217_163847"
Weight path 는 executor 브랜치에서 이제 함수 인자로 추가됐어!

2024-03-09 09:57 UTC, ProtossDragoon approved these changes

2024-03-09 09:57 UTC, merged