Feat datalake
slink-to-unlock/rpi-snailshell pull request #21
Opened 2024-06-22 09:22 UTC by ahnsukwoo

datalake를 구현했고, wandb에서 최신 모델을 다운로드하는 기능을 구현했읍니다.

2024-06-22 09:37 UTC, ProtossDragoon requested changes

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/main.py
> +        default=MODEL_WEIGHTS_PATH,  # Default weight path
`make test` 돌려서 테스트들 다 통과하는지 확인 필요

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/main.py
> +                '`picamera` 모듈 백엔드를 사용하고자 하는 경우 반드시 카메라를 사용해야 합니다.')
포매터 설정 확인 우리는 `yapf` 사용 중

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/main.py
> +                                 artifact_name="model-ai-sink-run",
- 이것들을 argparse 를 통해 전달받도록 수정
- 얘내들에 대한 테스트 코드는 어떻게 작성하면 좋을까

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/main.py
> +        default=MODEL_WEIGHTS_PATH,  # Default weight path
- 이 `weight_path` 가 무엇을 의미하는지 정확히 적어두면 좋을듯
- 지금은 wandb 가 다운로드받는 경로이기도 함
- 그럼 사용자가 다운을 안받고 그냥 돌리고싶으면 어떻게하지

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/main.py
> +                                 base_model_path=MODEL_WEIGHTS_PATH,
이 클래스 생성자 주석에 `base_model_path` 관련된 설명

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/main.py
> +    args.weight_path = MODEL_WEIGHTS_PATH
필요없음

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/models/model-ai-sink-run/config.json
> +}
모델파일이 여기 있으면 좋지 않음

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/models/model-ai-sink-run/training_args.bin
제외

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/models/model-ai-sink-run/model.safetensors
제외

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/models/model-ai-sink-run/config.json
제외

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +from collections import deque
안쓰임

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +from datetime import datetime
안쓰임

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +            target_fps=10,
tab 이 한줄 더들어감 ㅋㅋ

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +            user_id='user_1234',  # 추가: user_id 인자
`# 추가: user_id 인자` 주석 떼고 얘도 `argparse` 로 넘기자. 왜냐면 이건 프로그램에 귀속되는 값이다.

2024-06-22 09:37 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +            )
포매터

2024-06-30 11:33 UTC, ahnsukwoo commented on snailshell/main.py
> +                                 artifact_name="model-ai-sink-run",
디폴트 값으로 현재 우리의 경로를 적어놓음. 테스트는.... 존재 여부..?

2024-06-30 13:21 UTC, ProtossDragoon requested changes

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/main.py
> +    )
`action='store_true',` 와 같이 할수는 없나

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/main.py
> -        raise FileNotFoundError(f"{args.weight_path} 파일이나 디렉토리를 찾을 수 없습니다.")
남겨뒀다면 이거 지우면 안되지 않을까

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/main.py
> +MODEL_WEIGHTS_PATH = '/Users/sukcess/WorkSpace/slink-to-unlock/rpi-snailshell/snailshell/models/model-ai-sink-run'
이거 절대경로

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/main.py
> +MODEL_WEIGHTS_PATH = '/Users/sukcess/WorkSpace/slink-to-unlock/rpi-snailshell/snailshell/models/model-ai-sink-run'
1. 전역변수는 쓰지 말자
2. `weight_path` 의 required 은 빼되, 사용자가 입력할 수 있게 한다. 기본값도 지정하지 않는다.
3. 메인함수에서 `download_model` (이름 변경) 이 False 인 경우에 `weight_path` 가 지정되지 않았으면 오류가 발생하도록 한다. 안내와 함께. 이 설명을 `download_model`, `weight_path` 에 넣는다.
4. `download_model`이 True 이면 `wandb_artifact` 이랑 `wandb_project` 가 지정되어있어야만 하도록 assertion. 지정안돼있으면 오류 발생시키기. (테스트 케이스에 해당 경우의 수 추가. assertion 이 안되면 오류가 나도록)
5. 만약 `download_model` 이 True 이고, `weight_path` 가 지정되지 않은 경우, `os.path.join('.', '.cache')` 을 wandb 모델 디렉토리로 사용하도록 함.

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/main_test.py
> +            update_model='no',
이런 것들도 바꿔주고

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +        self.uploader = UploadLake(user_id)
`DatalakeUploader` `datalake_uploader`

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/tools/modelupdate.py
> +logging.basicConfig(level=logging.INFO,
이거 모든 파일마다 있어도 되는건지 확인

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/tools/modelupdate.py
파일 이름 `modeldownloader`

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/tools/modelupdate.py
> +class ModelUpdater:
modeldownloader

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/tools/uploadlake.py
datalakeuploader

2024-06-30 13:21 UTC, ProtossDragoon commented on snailshell/tools/uploadlake.py
> +        SERVICE_ACCOUNT_FILE = '/Users/sukcess/WorkSpace/sink/ai-sink-aa94e4cf6758.json'
절대경로

2024-06-30 14:30 UTC, ProtossDragoon requested changes

2024-06-30 14:30 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +            if key & 0xFF == ord('q'):
- 'r' 은 강제 분사용.
- '0' 또는 '1' 을 입력하도록.

2024-06-30 14:30 UTC, ProtossDragoon commented on snailshell/pipelines/base.py
> +            if key & 0xFF == ord('q'):
석우 생각이 일단 맞긴 함. 그런데 케이스 한개만 고려된거임.

2024-06-30 14:30 UTC, ProtossDragoon commented on snailshell/main_test.py
> +    def test_exception_when_model_path_empty(self, mock_args):
테스트 케이스 하나 부족

2024-07-06 07:01 UTC, ProtossDragoon approved these changes
일단인정

2024-07-06 07:02 UTC, merged